steps:
  # Etapa 1: Construção da Imagem do Container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: 
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_REPO_NAME:$COMMIT_SHA'
      - '.'

  # Etapa 2: Envio da Imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: 
      - 'push'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_REPO_NAME:$COMMIT_SHA'

  # Etapa 3: Implantação do First-App no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-first-app'
    entrypoint: 'gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'first-app'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_REPO_NAME:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'SERVER_NAME=first-app'

  # Etapa 4: Implantação do Second-App no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-second-app'
    entrypoint: 'gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'second-app'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_REPO_NAME:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'SERVER_NAME=second-app'


timeout: 1200s
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_REPO_NAME:$COMMIT_SHA'